branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - ci
      required_pull_request_reviews:
        required_approving_review_count: 2
      required_conversation_resolution: true
      allow_force_pushes: false
      allow_deletions: false
